const { Product } = require("../models");

module.exports = async () => {
  const productList = [
    {
      pic: "coffee/cappuccino.png",
      name: "Cappuccino",
      description:
        "Café espresso, leche vaporizada y abundante espuma de leche.",
      price: { base: "4.25", 350: "4.75", 450: "5.25" },
      stock: 99,
      featured: false,
      categoryId: 1,
      calories: 120,
    },
    {
      pic: "coffee/latte.png",
      name: "Latte",
      description: "Café espresso con leche vaporizada.",
      price: { base: "4.45", 350: "4.95", 450: "5.45" },
      stock: 10,
      featured: false,
      categoryId: 1,
      calories: 190,
    },
    {
      pic: "coffee/americano.png",
      name: "Americano",
      description:
        "Café espresso combinado con agua al mejor estilo americano..",
      price: { base: "3.25", 350: "3.75", 450: "4.25" },
      stock: 34,
      featured: false,
      categoryId: 1,
      calories: 15,
    },
    {
      pic: "coffee/mocha.png",
      name: "Mocha",
      description:
        "Chocolate con café espresso y leche al vapor, con crema batida.",
      price: { base: "4.75", 350: "5.25", 450: "5.75" },
      stock: 62,
      featured: false,
      categoryId: 1,
      calories: 360,
    },
    {
      pic: "coffee/mocha-white.png",
      name: "Mocha Blanco",
      description:
        "Chocolate blanco, shots de Espresso y leche vaporizada, con crema batida..",
      price: { base: "5.25", 350: "5.75", 450: "6.25" },
      stock: 123,
      featured: true,
      categoryId: 1,
      calories: 430,
    },
    {
      pic: "coffee/caramel-crunch-frappuccino.png",
      name: "Caramel Crunch Frappuccino",
      description:
        "Mezcla de salsa de caramelo oscuro, leche y hielo. ¡Cubierto con crema batida, llovizna de caramelo y azúcar caramelizada!",
      price: { base: "5.95", 350: "6.45", 450: "6.95" },
      stock: 28,
      featured: true,
      categoryId: 1,
      calories: 450,
    },
    {
      pic: "coffee/flat-white.png",
      name: "Flat White",
      description:
        "Shots de café ristretto con leche vaporizada que finaliza con un punto dibujado en la superficie.",
      price: { base: "4.75", 350: "5.25", 450: "5.75" },
      stock: 90,
      featured: false,
      categoryId: 1,
      calories: 170,
    },
    {
      pic: "coffee/caramel-macchiato.png",
      name: "Caramel Macchiato",
      description:
        "Vainilla y leche manchada con espresso, finalizada con el característico dibujo de caramelo.",
      price: { base: "5.25", 350: "5.75", 450: "6.25" },
      stock: 45,
      featured: false,
      categoryId: 1,
      calories: 250,
    },
    {
      pic: "coffee/espresso.png",
      name: "Espresso",
      description:
        "Auténtico sabor de nuestro espresso: intenso y suave, con rica crema dorada.",
      price: { base: "2.45", 350: "2.95", 450: "3.45" },
      stock: 75,
      featured: false,
      categoryId: 1,
      calories: 5,
    },
    {
      pic: "coffee/latte-matcha.png",
      name: "Latte Matcha",
      description:
        "Bebida suave y cremosa de matcha, perfecta para disfrutar en cualquier momento.",
      price: { base: "5.45", 350: "5.95", 450: "6.45" },
      stock: 25,
      featured: true,
      categoryId: 1,
      calories: 200,
    },
    {
      pic: "coffee/mocha-frappe.png",
      name: "Frappe Mocha",
      description:
        "Bebida dulce, cremosa y fría, con el rico sabor del chocolate y el café.",
      price: { base: "5.75", 350: "6.25", 450: "6.75" },
      stock: 34,
      featured: true,
      categoryId: 1,
      calories: 420,
    },
    {
      pic: "coffee/tea-english.png",
      name: "Té Negro Inglés",
      description:
        "Té maltoso de la India con tés brillantes de Sri Lanka y Keemun chino.",
      price: { base: "2.95", 350: "3.45", 450: "3.95" },
      stock: 0,
      featured: false,
      categoryId: 1,
      calories: 0,
    },
    {
      pic: "coffee/ultra-caramel.png",
      name: "Caramel Frappuccino",
      description:
        "Mocha Frappuccino envuelto en capas de crema batida, café frío y salsa de caramelo oscuro.",
      price: { base: "5.95", 350: "6.45", 450: "6.95" },
      stock: 15,
      featured: false,
      categoryId: 1,
      calories: 500,
    },
    {
      pic: "bakery/brownie-chocolate.png",
      name: "Brownie de Chocolate",
      description: "Delicioso brownie de chocolate con nueces.",
      price: { base: "3.95" },
      stock: 12,
      featured: false,
      categoryId: 2,
      calories: 280,
    },
    {
      pic: "bakery/caramel-slice.png",
      name: "Slice de Caramelo",
      description:
        "Masa de hojaldre con capas de caramelo pegajoso y chocolate con leche.",
      price: { base: "2.95" },
      stock: 120,
      featured: false,
      categoryId: 2,
      calories: 180,
    },
    {
      pic: "bakery/chip-cookie.png",
      name: "Galleta con chispas de Chocolate",
      description:
        "Galleta con generosos trozos de chocolate con leche, horneada a la perfección.",
      price: { base: "2.95" },
      stock: 250,
      featured: false,
      categoryId: 2,
      calories: 200,
    },
    {
      pic: "bakery/cake-vanilla.png",
      name: "Tarta de Vainilla",
      description: "Tarta suave y esponjosa con sabor a vainilla.",
      price: { base: "3.95" },
      stock: 20,
      featured: false,
      categoryId: 2,
      calories: 250,
    },
    {
      pic: "bakery/choc-muffin-1.png",
      name: "Muffin de Chocolate",
      description:
        "Muffin rico y húmedo, perfecto para los amantes del chocolate.",
      price: { base: "2.95" },
      stock: 100,
      featured: false,
      categoryId: 2,
      calories: 300,
    },
    {
      pic: "bakery/croissant-chocolate-shadow.png",
      name: "Chocolate Croissant",
      description:
        "Dos generosos trozos de chocolate envueltos en un croissant de mantequilla con capas suaves y hojaldradas y una corteza dorada",
      price: { base: "3.45" },
      stock: 130,
      featured: false,
      categoryId: 2,
      calories: 280,
    },
    {
      pic: "bakery/brekky-roll-beacon.png",
      name: "Sandwich de Bacon",
      description: "Sandwich de tocino, huevo y queso, perfectamente tostado.",
      price: { base: "3.95" },
      stock: 32,
      featured: false,
      categoryId: 2,
      calories: 300,
    },
    {
      pic: "bakery/brekky-roll-vegan.png",
      name: "Sandwich Vegano",
      description:
        "Sandwich a base de plantas con tocino de origen vegetal, huevo de tofu y salsa barbacoa.",
      price: { base: "3.95" },
      stock: 19,
      featured: true,
      categoryId: 2,
      calories: 250,
    },
    {
      pic: "bakery/sandwich-vegan-grilled.png",
      name: "Sandwich vegan grill",
      description:
        "Un sándwich saludable y sustancioso elaborado con verduras a la parrilla, incluyendo pimiento, berenjena, batata y trozos de queso feta vegano.",
      price: { base: "4.50" },
      stock: 40,
      featured: false,
      categoryId: 2,
      calories: 280,
    },
    {
      pic: "bakery/toastie-cheesetomato.png",
      name: "Tostadas con jamón y queso",
      description:
        "Jamón ahumado con nogal y queso suizo derretido envueltos en un croissant de mantequilla con capas suaves y hojaldradas y una corteza dorada",
      price: { base: "4.95" },
      stock: 60,
      featured: false,
      categoryId: 2,
      calories: 200,
    },
    {
      pic: "bakery/wrap-chickenavocado.png",
      name: "Wrap de pollo y palta",
      description:
        "Tierna pechuga de pollo y lechuga fresca y crujiente con aguacate cremoso, todo envuelto en una tortilla integral..",
      price: { base: "3.95" },
      stock: 80,
      featured: false,
      categoryId: 2,
      calories: 250,
    },
    {
      pic: "categories/beans-white.png",
      name: "Café Arábica",
      description: "Paquete de 500g de granos de café Arábica de alta calidad.",
      price: { base: "8.5" },
      stock: 30,
      featured: false,
      categoryId: 3,
      calories: 0,
    },
    {
      pic: "categories/beans-black.png",
      name: "Café Robusta",
      description:
        "Paquete de 500g de granos de café Robusta con un sabor fuerte y rico.",
      price: { base: "8.5" },
      stock: 25,
      featured: false,
      categoryId: 3,
      calories: 0,
    },
    {
      pic: "categories/beans.png",
      name: "Blend de la casa",
      description:
        "Paquete de 500g de una mezcla especial de granos Arábica y Robusta.",
      price: { base: "9.5" },
      stock: 20,
      featured: false,
      categoryId: 3,
      calories: 0,
    },
  ];

  await Product.bulkCreate(productList);
  console.log("Product seeder has been ran.");
};
